// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edjvvooymnljxxugkfju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkanZ2b295bW5sanh4dWdrZmp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMTY0MTgsImV4cCI6MjA3MTc5MjQxOH0.UK7xe4P6ODsnTZjZq3iH4Zo-LY6a5LtVzxcym87y2PU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});